### ISSUE TITLE
Improved sentence detection

### ISSUE THREAD

**Issue by trinker** [Rexamine/stringi#184]
I love **stringi**'s speed.  The sentence detection of the package is less accurate than the **openNLP**/**NLP** approach to sentence detection.  Someone has opened an issue on SO regarding this (I offered a bounty on the question):

http://stackoverflow.com/q/31865511/1000343

Is there a way to match **openNLP**/**NLP**'s accuracy and retain **stringi**'s speed?

**Comment by trinker** [comment]
The example:

**openNLP**

```r
library(NLP) # NLP_0.1-7  
string <- as.String("Mr. Brown comes. He says hello. i give him coffee.")

library(openNLP) # openNLP_0.2-5  

sentence_token_annotator <- Maxent_Sent_Token_Annotator(language = "en")  
boundaries_sentences<-annotate(string, sentence_token_annotator)  
string[boundaries_sentences]  

[1] "Mr. Brown comes."   "He says hello."     "i give him coffee."  
```

**stringi**

```r
library(stringi) # stringi_0.5-5  

stri_split_boundaries( string , opts_brkiter=stri_opts_brkiter('sentence'))

[[1]]  
 [1] "Mr. "                              "Brown comes. "                    
 [3] "He says hello. i give him coffee."
```

**Comment by gagolews** [comment]
Text boundary (in this case, sentence boundary) analysis in ICU (and thus in stringi) is governed by the rules described in Unicode [UAX29](http://unicode.org/reports/tr29/#Sentence_Boundaries), see also [ICU Users Guide on the topic](http://userguide.icu-project.org/boundaryanalysis). We read:

> [The Unicode rules] cannot detect cases such as “...Mr. Jones...”; more sophisticated tailoring would be required to detect such cases.

In other words, this cannot be done without a custom dictionary of non-stop words, which in fact is implemented in `openNLP`. A few possible scenarios to incorporate stringi for performing this task would therefore include:

1.  Use `stri_split_boundaries` and then write a function deciding on which incorrectly split tokens should be joined.
2.  Manually input non-breaking spaces into the text (possibly after dots following *etc.*, *Mr.*, *i.e.* and so on (note that this in fact is required when preparing documents in LaTeX -- otherwise you get too huge spaces between words)

and so on.

One thing I could try to do in stringi (in the future) is to give access to an break iterator's interface that allows for inputting custom break/no-break rules. Yet, now it's not possible.

**Comment by srrussel74** [comment]
The stringi package works with a list rules how to break lines into sentences. I believe it works fast because of use of strings as objects. And I notice openNLP works with  a sort of model from a learning procedure to correct breaking into sentences. is it right? If yes, then it is possible to change set of rules by the model?

**Comment by gagolews** [comment]
As far as I remember, the ICU guys will make that feature available in ICU 57 (?)

**Comment by gagolews** [comment]
OK, this has been introduced in ICU 56.

```
> stri_split_boundaries("Mr. Jones and Mrs. Brown are very happy. So am I, Prof. Smith.", type="sentence", locale="@ss=standard")
[[1]]
[1] "Mr. Jones and Mrs. Brown are very happy. "
[2] "So am I, Prof. Smith."                    

> stri_split_boundaries("Mr. Jones and Mrs. Brown are very happy. So am I, Prof. Smith.", type="sentence", locale="@ss=none")
[[1]]
[1] "Mr. "                   "Jones and Mrs. "        "Brown are very happy. "
[4] "So am I, Prof. "        "Smith."   
```
